//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTH_NumberAndTransportName
    {
        public int TTH { get; set; }
        public string ProductName { get; set; }
        public string Transport { get; set; }
    }
}
